### ISSUE TITLE
"Try in the live editor" not working

### ISSUE THREAD

**Issue by desaintflorent** [kylekatarnls/business-time#17]
Hello, 
I was checking this package and the link to try in the live editor are not working anymore.
Also I'm not sure to understand what business-time bring on top of spatie opening-hours package ? what is the difference except it had business holidays ?

Kind regards

**Comment by kylekatarnls** [comment]
Hi,

The live editor will be back in a few days.

The project spatie/opening-hours (I also maintain for about a year) is a dependency-free library.

business-time is:
- a mixin for Carbon giving direct access of opening-hours methods on Carbon/CarbonImmutable instances (Carbon::now()->nextClose() returns a Carbon instance) and so it also allows string and Carbon-understandable types as input
- a few more shortcuts
- a provider for Laravel
- [business-day](https://github.com/kylekatarnls/business-day)
- methods that combine both holidays and opening hours like [isBusinessOpen
 and isBusinessClosed](https://github.com/kylekatarnls/business-time#isbusinessopen--isopenexcludingholidays)
