### ISSUE TITLE
Cannot use addOpenHours with LOCAL_MODE

### ISSUE THREAD

**Issue by Naghal** [kylekatarnls/business-time#31]
Hi, I am unable to use `addOpenHours()` when setting the opening hours on a carbon date instance. It works if I set it using `Carbon::setOpeningHours`.

I was able to verify that the opening hours were correctly set on my carbon date instance by calling `getOpeningHours()`. However, calling `addOpenHours()` immediately threw `InvalidArgumentException('Opening hours have not been set.')`

I need to set the opening hours on the carbon date instance because opening hours can change at runtime.

**Minimal reproduction**
1.  Load the mixin
```php
<?php

namespace App\Providers;

use Illuminate\Support\ServiceProvider;
use Cmixin\BusinessTime;
use Carbon\Carbon;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Register any application services.
     *
     * @return void
     */
    public function register()
    {
        //
    }

    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
        BusinessTime::enable(Carbon::class);
    }
}

```
2. Parse a date with carbon and then set the opening hours
```php
$c = Carbon::parse($this->openingDate);
    $c->setOpeningHours([
            'monday' => ['09:00-12:00', '13:00-18:00'],
            'tuesday' => ['09:00-12:00', '13:00-18:00'],
            'wednesday' => ['09:00-12:00'],
            'thursday' => ['09:00-12:00', '13:00-18:00'],
            'friday' => ['09:00-12:00', '13:00-20:00'],
            'saturday' => ['09:00-12:00', '13:00-16:00'],
    ]);
```
3. Call `addOpenHours()` on the carbon date instance
`$c->addOpenHours(10);`
At this point, `InvalidArgumentException` is thrown.
If I call `$c->getOpeningHours()` instead, I get the following:
![image](https://user-images.githubusercontent.com/29404633/87453774-0ae77880-c5d1-11ea-83aa-328a6d0efacc.png)

**Comment by kylekatarnls** [comment]
Thank you. I identified the issue. I'm working on it.

**Comment by kylekatarnls** [comment]
This should be fixed, please try to update the `cmixin/business-time` **1.7.2**.

**Comment by Naghal** [comment]
Thank you, the problem is fixed.
