### ISSUE TITLE
isOpenOn('Y-m-d') holiday filter issue

### ISSUE THREAD

**Issue by joecampo** [kylekatarnls/business-time#34]
Hey there,

First off - thank you so much for package, it really is awesome!

### Issue

When attempting to check if a date is open on a string formatted date e.g.

```php
Carbon::isOpenOn('2020-07-04');
```

and `holidaysAreClosed` is set to true it produces the following error:

```php
PHP Error:  Call to undefined method DateTime::isHoliday() in /vendor/cmixin/business-time/src/BusinessTime/DefinitionParser.php on line 194
```

### Example

[Here is an example in the live editor](https://try-carbon.herokuapp.com/?input=BusinessTime%3A%3Aenable%28Carbon%3A%3Aclass%2C%20%5B%0A%20%20%27monday%27%20%3D%3E%20%5B%2709%3A00-12%3A00%27%2C%20%2713%3A00-18%3A00%27%5D%2C%0A%20%20%27tuesday%27%20%3D%3E%20%5B%2709%3A00-12%3A00%27%2C%20%2713%3A00-18%3A00%27%5D%2C%0A%20%20%27wednesday%27%20%3D%3E%20%5B%2709%3A00-12%3A00%27%5D%2C%0A%20%20%27thursday%27%20%3D%3E%20%5B%2709%3A00-12%3A00%27%2C%20%2713%3A00-18%3A00%27%5D%2C%0A%20%20%27friday%27%20%3D%3E%20%5B%2709%3A00-12%3A00%27%2C%20%2713%3A00-20%3A00%27%5D%2C%0A%20%20%27saturday%27%20%3D%3E%20%5B%2709%3A00-12%3A00%27%2C%20%2713%3A00-16%3A00%27%5D%2C%0A%20%20%27sunday%27%20%3D%3E%20%5B%5D%2C%0A%20%20%27holidaysAreClosed%27%20%3D%3E%20true%2C%0A%20%20%27exceptions%27%20%3D%3E%20%5B%0A%20%20%20%20%272016-11-11%27%20%3D%3E%20%5B%2709%3A00-12%3A00%27%5D%2C%0A%20%20%20%20%272016-12-25%27%20%3D%3E%20%5B%5D%2C%0A%20%20%20%20%2701-01%27%20%3D%3E%20%5B%5D%2C%20%2F%2F%20Recurring%20on%20each%201st%20of%20january%0A%20%20%20%20%2712-25%27%20%3D%3E%20%5B%2709%3A00-12%3A00%27%5D%2C%20%2F%2F%20Recurring%20on%20each%2025th%20of%20december%0A%20%20%5D%2C%0A%20%20%27holidays%27%20%3D%3E%20%5B%0A%20%20%20%20%27region%27%20%3D%3E%20%27us-ny%27%2C%20%2F%2F%20Load%20the%20official%20list%20of%20holidays%20from%20USA%20-%20New%20York%0A%20%20%20%20%27with%27%20%3D%3E%20%5B%0A%20%20%20%20%20%20%27labor-day%27%20%3D%3E%20null%2C%20%2F%2F%20Remove%20the%20Labor%20Day%20%28so%20the%20business%20is%20open%29%0A%20%20%20%20%20%20%27company-special-holiday%27%20%3D%3E%20%2704-07%27%2C%20%2F%2F%20Add%20some%20custom%20holiday%20of%20your%20company%20%0A%20%20%20%20%5D%2C%0A%20%20%5D%2C%0A%5D%29%3B%0A%0A%0A%0Avar_dump%28Carbon%3A%3AisOpenOn%28%272020-07-04%27%29%29%3B%0A)

### Trying to solve

After taking a look at the [DefinitionParser@194](https://github.com/kylekatarnls/business-time/blob/fc176196fde00b6c1d092e5b1249a687dca76857/src/BusinessTime/DefinitionParser.php#L194) expect the date object passed into the closure to be a Carbon instance, but after source diving the new implementation in [spatie/opening-hours](https://github.com/spatie/opening-hours) a DateTime object is what is being passed into the filters.

I was going to submit a PR, but I'm not sure the best way to go around fixing this as I don't see an easy way to parse out the holidays to check the DateTime object. Appreciate your time and help!

### Using:

Laravel 7.28.1 (schedule enabled to \Illuminate\Support\Carbon)
PHP 7.4.9

**Comment by kylekatarnls** [comment]
Good point I did not test with `holidaysAreClosed`
