### ISSUE TITLE
Problem with Laravel & Holidays

### ISSUE THREAD

**Issue by heikokrebs** [kylekatarnls/business-time#37]
Hey,

first of all: thanks for the awesome work!

I ran into a problem when using this package in a Laravel project. When i set `holidaysAreClosed` to true and use functions like `nextBusinessOpen()` i get an exception:

> Error
> Class name must be a valid object or a string
>
> BusinessTime\MixinBase::BusinessTime\{closure}
> vendor/cmixin/business-time/src/BusinessTime/MixinBase.php:147

`$carbonClass` is supposed to be a class name or object but it is an array with some Carbon-Classnames.

**Comment by kylekatarnls** [comment]
Thanks, it regressed in 1.9.0, it's now fixed.

**Comment by heikokrebs** [comment]
That was super fast, thanks a lot @kylekatarnls!
