### ISSUE TITLE
DiffInBusiness* does not work with LOCAL_MODE

### ISSUE THREAD

**Issue by Naghal** [kylekatarnls/business-time#39]
Hi!
I am having the same problem as in issue #31, but this time with diffInBusiness methods.
I am using latest version of this package. (1.9.1)

Example:

```php
$openingHour = $this->getOpeningHour();
$openingHourSchedule = $openingHour->getSerializedSchedule($this->openingHourArraySerialiser);
$openingDate = Carbon::parse($this->ticket->getSlaStartPointDate())->setOpeningHours($openingHourSchedule);
$endDate = Carbon::parse($this->ticket->ClosedDate)->setOpeningHours($openingHourSchedule);
```

if I call `$openingDate->getCurrentOpenTimePeriod()`, it returns the correct opening hours
![image](https://user-images.githubusercontent.com/29404633/100127648-52b6c000-2e4d-11eb-8224-878ca78c88cf.png)

However, I cannot call `$openingDate->diffInBusinessHours($endDate);` as it result in the following error:
```
exception: "BusinessTime\Exceptions\InvalidArgumentException"
file: "/app/vendor/cmixin/business-time/src/BusinessTime/MixinBase.php"
line: 300
message: "Opening hours have not been set."
```

**Comment by kylekatarnls** [comment]
This is fixed in 1.9.2. Thanks for the report.

**Comment by kylekatarnls** [comment]
Side note: the `$endDate` here does not need to have `$openingHourSchedule` set, only the start date opening hours are used.

**Comment by Naghal** [comment]
Thank you, it is working!
