### ISSUE TITLE
TypeError trying to get nextOpen

### ISSUE THREAD

**Issue by mikemand** [kylekatarnls/business-time#5]
Hi Kyle,

I'm using your Business Day and Business Time packages in a new Laravel 5.7 app. When trying to get [the next open](https://github.com/kylekatarnls/business-time#nextopen) time (in a Unit Test for now), I'm receiving the following error:

> TypeError: Argument 1 passed to Tests\Unit\OpeningHoursTest::Tests\Unit\{closure}() must be an instance of Illuminate\Support\Carbon, instance of DateTime given, called in /vendor/spatie/opening-hours/src/OpeningHours.php on line 187

I traced it back to here: https://github.com/kylekatarnls/business-time/blob/670652b4d6c3de99daef7f7f1a5f3bc04b42d0e8/src/BusinessTime/MixinBase.php#L123

More specifically, `$this->safeCallOnOpeningHours($callee, $this->toDateTime())`. It looks like Spatie's package is expecting a Carbon instance, instead of a \DateTime instance. If I change it to `$this->safeCallOnOpeningHours($callee, $this)`, my test passes and I get the expected nextOpen date and time.

I do not know what other side-effects would occur from this change. Please let me know if you want me to open a pull request to make this change.

Here is my current setup:

- cmixin/business-day v1.2.0
- cmixin/business-time v1.1.0
- spatie/opening-hours v2.0.0

```json
"require": {
	...
	"cmixin/business-time": "^1.1",
	"kylekatarnls/laravel-carbon-2": "^1.0.0",
	"nesbot/carbon": "2.11.0 as 1.34.0",
	...
}
```

And my test:

```php
$this->assertEquals(Carbon::create(2019, 12, 26, 13)->format('Y-m-d H:i'), Carbon::create(2019, 12, 24, 23)->nextOpen()->format('Y-m-d H:i'));
```

**Comment by mikemand** [comment]
I should probably note that I'm using Laravel's Carbon wrapper, instead of Carbon itself - just to keep things consistent with what Laravel returns from models with date/time casts.

**Comment by kylekatarnls** [comment]
I need your `BusinessTime::enable(Carbon::class, [...])` code to inspect. It probably contains a Carbon typing that should not be there.

**Comment by mikemand** [comment]
Hi Kyle,

I have the following in my `AppServiceProvider`'s `boot` method:

```php
use Illuminate\Support\Carbon;

BusinessTime::enable(Carbon::class);
// Set company-wide holidays
Carbon::setHolidays('app', [
    'easter' => function ($year) {
        return \date('d/m', \easter_date($year));
    },
    'independence-day' => '04/07',
    'thanksgiving' => function ($year) {
        $date = new DateTime("fourth thursday of november $year");

        return $date->format('d/m');
    },
    'christmas' => '25/12',
]);
Carbon::setHolidaysRegion('app');
```

And then in my test, I'm setting the opening hours (since I have multiple locations I need to support, the opening hours will be set "on the fly" from whichever location is being looked at):

```php
use Illuminate\Support\Carbon;

protected function setUp()
    {
        parent::setUp();

        Carbon::setOpeningHours([
            'monday' => ['13:00-18:00'],
            'tuesday' => [],
            'wednesday' => ['13:00-18:00'],
            'thursday' => ['13:00-18:00'],
            'friday' => ['13:00-20:00'],
            'saturday' => ['13:00-16:00'],
            'sunday' => ['13:00-18:00'],
            'exceptions' => [
                '01-01' => ['13:00-18:00'],
                function (Carbon $date): ?array {
                    if ($date->isHoliday()) {
                        // Or use ->isObservedHoliday() and set observed holidays:
                        // https://github.com/kylekatarnls/business-day#setobservedholidayszone
                        switch ($date->getHolidayId()) {
                            // If the ID "christmas" exists in the selected holidays region and matches the current date:
                            // case 'christmas':
                            //     return ['10:00-12:00'];
                            default:
                                return [
                                    'hours' => [],
                                    'data' => [
                                        'reason' => 'Closed for ' . $date->getHolidayName(),
                                    ],
                                ];
                        }
                    }

                    // Else, typical day => use days of week settings
                    return null;
                },
            ],
        ]);
    }
```

**Comment by kylekatarnls** [comment]
It should be allowed here. I will check why it happens. Meanwhile, you can do:

```php
function (date): ?array {
  $date = Carbon::instance($date);
```

**Comment by mikemand** [comment]
Hi Kyle,

That worked! How odd. Thank you for your help. I will leave it up to your discretion when to close this issue. 👍

**Comment by kylekatarnls** [comment]
Fixed in https://github.com/kylekatarnls/business-time/releases/tag/1.2.0

**Comment by mikemand** [comment]
Thank you Kyle! 👍
