### ISSUE TITLE
PHP Warning:  Cannot bind an instance to a static closure

### ISSUE THREAD

**Issue by makroxyz** [kylekatarnls/business-time#52]
I'm on PHP 8.0 and Laravel 8.62

It happens when calling every business-time or business-date functions

**Comment by kylekatarnls** [comment]
Without a minimum project example to reproduce and the stack trace of the error I can only guess you get this issue https://github.com/briannesbitt/Carbon/issues/2396

This error is muted with `@` and inside a tr-catch. It's used to detect if the closure is static as there is no other way to know in PHP.

You likely have a shutdown function checking `error_get_last()` or a custom exception handler that did not respect the mute-instruction as it does not happen with a fresh install of Laravel and this package.

**Comment by jonny-dengro** [comment]
Same error here.

Simplified version of my code to help reproduce:

```
    public function calculateTimeToFirstContact(): float
    {
        // As a second argument you can set default opening hours:
        BusinessTime::enable(Carbon::class, [
            'monday' => ['09:00-17:00'],
            'tuesday' => ['09:00-17:00'],
            'wednesday' => ['09:00-17:00'],
            'thursday' => ['09:00-17:00']
            'friday' => ['09:00-17:00'],
            'saturday' => [],
            'sunday' => []
            // You can use the holidays provided by BusinessDay and mark them as fully closed days using 'holidaysAreClosed'
            'holidaysAreClosed' => true,
            // Note that exceptions will still have the precedence over the holidaysAreClosed option.
            'holidays' => [
                'region' => 'gb-national',
            ],
        ]);

        // ensure we have some opening hours before attempting to calculate diff
        /** @phpstan-ignore-next-line */
        error_reporting(0);
        $timeRange = Carbon::getCurrentOpenTimeRange();

        if ($timeRange) {
            /** @phpstan-ignore-next-line */
            return Carbon::parse('2022-01-07 09:00:00')
                ->diffInBusinessSeconds('2022-01-12 17:00:00');
        }

        return 0;
    }
```

**Comment by kylekatarnls** [comment]
This code does not allow to reproduce the error.

Here is a summary of https://github.com/briannesbitt/Carbon/issues/2396 as applied to business-time

If you set `error_reporting(0)` with an error handler that respects the error muter, you should not have any issue:
```php
BusinessTime::enable(Carbon::class, ['monday' => ['05:00-17:00']]);

set_error_handler(static function (
    int $errno,
    string $errstr,
    string $errfile = '',
    int $errline = 0,
    array $errcontext = []
): bool {
    if (!(error_reporting() & $errno)) {
        return false;
    }

    throw new ErrorException($errstr, $errno, $errno, $errfile, $errline);
});

error_reporting(0);

echo Carbon::getCurrentOpenTimeRange();
```

But if your error handler does not respect the error muter, e.g. does not have this part:
```php
    if (!(error_reporting() & $errno)) {
        return false;
    }
```

Then Carbon is unable to catch properly this error (which is expected to happen and is muted on purpose because there is no other way to know a closure is static) and apply the proper fallback.
