### ISSUE TITLE
IDE Helper Files part of the distribution

### ISSUE THREAD

**Issue by benfreke** [kylekatarnls/business-time#54]
Hi

Great plugin. 

I'm using PhpStorm, and when Carbon is included in my project, it is complaining about multiple Definitions.

I think this is due to extra files being included in the distribution when they shouldn't be. Specifically the entire `types` and `.github` directories.  

Are you open to a PR fixing this, or did you want to fix this yourself? Given it'll be part of the build process I'm not certain this is something I could/should fix?

![Screen Shot 2022-05-06 at 4 37 39 pm](https://user-images.githubusercontent.com/2102440/167079765-bdc47308-3e90-41f7-a85b-0333c38d0bc5.png)

**Comment by kylekatarnls** [comment]
Hello,

Removing `types` will break the auto-completion. It's there to enable the following feature:
![image](https://user-images.githubusercontent.com/5966783/168429676-629be9e3-e857-4d5f-85d4-12bd585f8721.png)

If you remove it, only the methods business-time will remain:
![image](https://user-images.githubusercontent.com/5966783/168429838-cea2550d-55a9-4f51-96bb-371b1673015e.png)

Multiple definitions is actually expected to happen when using the macro/mixin pattern as methods are added to an existing class that is not itself modified.

If there is an other syntax that IDEs would understand (still provide the auto-completion as per the screenshots above) and not trigger any multiple-definitions notice, I'm OK to merge this change. But removal or exclusion from the distribution package is not an option.
