### ISSUE TITLE
No Holidays when using Schedule instances

### ISSUE THREAD

**Issue by TNTLarsn** [kylekatarnls/business-time#62]
[![Test on PHPSandbox](https://phpsandbox.io/img/brand/badge.png)](https://phpsandbox.io/n/04ui3)

**Comment by kylekatarnls** [comment]
I have holidays:
https://phpsandbox.io/e/x/7548o?layout=EditorPreview&defaultPath=%2F&theme=dark&showExplorer=no&openedFiles=

Can you confirm custom holidays (`holidays.with` option) is missing? As this is the only option not giving expected result as per the given example.

**Comment by TNTLarsn** [comment]
No, I can not confirm this,  as of your holiday `"2022-12-25 09:40:00"` is a sunday anyway.  Try `"2023-12-25 09:40:00" `which is a monday and `->isopen()` will return  `true`

**Comment by kylekatarnls** [comment]
Sorry for the delay, it's now fixed in 1.12.1.
