### ISSUE TITLE
Method Carbon\CarbonImmutable::swapDateTimeParam does not exist.

### ISSUE THREAD

**Issue by TNTLarsn** [kylekatarnls/business-time#65]
getting an Exception when calling `getHolidayName`  Method using `BusinessTime\Schedule` and `CarbonImmutable`
Maybe related to (https://github.com/kylekatarnls/business-time/issues/62)?

 https://phpsandbox.io/e/x/wb05t?layout=EditorPreview&defaultPath=%2F&theme=dark&showExplorer=no&openedFiles=

**Comment by kylekatarnls** [comment]
Thanks for the report, it will be fixed in the next release of [cmixin/business-day](https://github.com/kylekatarnls/business-day)

**Comment by kylekatarnls** [comment]
You can now `composer u cmixin/business-day` to get the version `1.16.3` and it will fix this issue.
