### ISSUE TITLE
Find out if it's a public holiday but still open

### ISSUE THREAD

**Issue by informatJonas** [kylekatarnls/business-time#67]
How can I find out if a weekday is a public holiday but is still open?

Can I use `carbon.holidaysAreClosed` to influence these options?

**Comment by kylekatarnls** [comment]
Hello, are your referring to the notion of observance that exist in some countries? In the semantic of this library, it's not considered a holiday. This would need to emebed list of them for all countries and add another set of methods for that.

`holidaysAreClosed` is an option to say: "Is this business closed on observed holidays"

**Comment by informatJonas** [comment]
What does this "observed holidays" actually mean?

**Comment by informatJonas** [comment]
I have now solved it like this: `!$dateObject->getOpeningHours()->forDate($dateObject)->isEmpty()`.

**Comment by kylekatarnls** [comment]
> What does this "observed holidays" actually mean?

An actual holiday (that is observed by the country so a typical business is closed on this day)

By opposition to an "observance" which is a term for what you mentioned in your original message as:
> a weekday is a public holiday but is still open

Those terms are common in USA but definitions of "holiday" varies from one country to another and business context on the top. 

So I cannot provide further assistance without more details.
